apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-lqvtdcpn-gitops
  description: This is GitOps manifest for go-lqvtdcpn   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=go-lqvtdcpn
    backstage.io/kubernetes-id: go-lqvtdcpn 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: go-lqvtdcpn
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-lqvtdcpn
